### ISSUE TITLE
Find a place for DV external tool manifest redirecting for binder

### ISSUE THREAD

**Issue by Xarthisius** [data-exp-lab/girder_ythub#10]
Unaddressed part of #9 by @pdurbin

Also, I'm looking for a home for this external tool manifest you originally posted at https://github.com/IQSS/dataverse/issues/6807#issuecomment-611794683

```
{
  "displayName": "Binder",
  "description": "Run on Binder",
  "scope": "dataset",
  "type": "explore",
  "toolUrl": "https://girder.hub.yt/api/v1/ythub/dataverse",
  "toolParameters": {
    "queryParameters": [
      {
        "datasetPid": "{datasetPid}"
      },
      {
        "siteUrl": "{siteUrl}"
      },
      {
        "key": "{apiToken}"
      }
    ]
  }
}
```

Could we maybe add it to the README of this "girder_ythub" repo. We have a rule that external tool manifests shouldn't be hosted in the Dataverse guides. That's why we asked you and other Whole Tale folks to set up https://wholetale.readthedocs.io/en/stable/users_guide/integration.html#dataverse-external-tools (thanks again!).

**Comment by pdurbin** [comment]
@Xarthisius me again! I just talked to our PI and we're going to [enable the Binder button in Harvard Dataverse](https://github.com/IQSS/dataverse.harvard.edu/issues/208) soon (maybe as soon as today!).

Meanwhile we want to add Binder to the list of external tools: https://guides.dataverse.org/en/5.12.1/admin/external-tools.html (Whole Tale has been lonely as the only dataset-level tool for years!) 😄 

![Screen Shot 2023-01-27 at 11 24 10 AM](https://user-images.githubusercontent.com/21006/215138748-61f0048d-4d55-42aa-8015-316ca6c5681e.png)

Any thoughts on where the JSON manifest can be hosted?

Thanks again for running the girder.hub.yt service! Without it, we could be able to enable the Binder button! 🚀 ❤️

**Comment by pdurbin** [comment]
For anyone arriving on this issue from https://guides.dataverse.org/en/latest/admin/external-tools.html (Dataverse 6.1 and earlier), there is a new external tool JSON manifest file for Binder available at https://github.com/IQSS/dataverse-binder-redirect

The Dataverse team has updated its guides to link there rather than this issue:

- https://github.com/IQSS/dataverse/pull/10361

See also this post to the Dataverse mailing list: https://groups.google.com/g/dataverse-community/c/5kQhpKTOVvw/m/xUbPNEmMAQAJ

@Xarthisius thanks so much for hosting the redirect service for so long and for implementing Binder support in repo2docker in the first place! I'd say it's safe to close this issue if you like.
